### ISSUE TITLE
Can't login to Spotify

### ISSUE THREAD

**Issue by zimnx** [mauimauer/portify#110] opened 2014-05-29 17:08 UTC
Hey, 
I encountered problem with logging into Spotify account. Google account works fine, but after i enter my credentials nothing happens. When i enter wrong login/password i have a notification that they are not correct. Anyone have the same issue or know possible fix?

**Comment by computeralex92** [comment] 2014-05-29 19:43
I have the same problem; i try to check if there is a problem with my installation, but everything is fine.

It's possible in my opinion that Spotify change the API...

**Comment by MWEJ** [comment] 2014-05-30 07:21
I have the exact same problem. :(

**Comment by simongray** [comment] 2014-05-30 08:03
Same issue here. Google login works, no output whatsoever at Spotify login (using device ID and password).

I'm using it in Denmark after Google Music All Access just become available here.

**Comment by j000** [comment] 2014-05-30 13:17
Same issue. Spotify login does nothing.
BTW. Tried using spotify-web@1.2.0, nothing changed.

**Comment by zekus** [comment] 2014-05-30 14:37
same here, no output... tried spotify-web from the github master repo too

**Comment by chossimbaone** [comment] 2014-06-01 07:23
Same issue here. Google login works, but spotify login just stalles.

**Comment by computeralex92** [comment] 2014-06-01 09:37
I think i have found the problem:

Error: Account subscription status not Spotify Premium
    at SpotifyConnection._onmessage (/root/portify/data/node_modules/spotify-web/lib/connection/connection.js:135:15)
    at SpotifyConnection.EventEmitter.emit (events.js:98:17)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/root/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/root/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/root/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/root/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/root/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)

**Comment by zimnx** [comment] 2014-06-01 09:48
I have Spotify Premium. That's not an issue. I think that API changed.

**Comment by computeralex92** [comment] 2014-06-01 09:55
I search for the API Implementation for Nodejs and found this issue:

https://github.com/TooTallNate/node-spotify-web/issues/87

**Comment by mrbormeth** [comment] 2014-06-02 09:47
Same problem :) Can login in with google just fine, spotify login just closes the app and nothing more. :)

**Comment by maedox** [comment] 2014-06-03 11:44
Same thing here. Nothing happens at all when pressing Submit on the Spotify login screen. :-/

**Comment by Kepilif** [comment] 2014-06-03 13:20
Exactly the same. I am a user of spotify premium.

**Comment by zimnx** [comment] 2014-06-03 13:23
Please dont's spam whole topic(and my email ;P) with useless information "me too". That's a real issue, that is already known. I hope someone who know node.js will fix it soon.

**Comment by NeoGeneration** [comment] 2014-06-04 16:43
Tried to make a push but couldn't do it. Here is the fix. Change the following function in portify/data/node_modules/spotify-web/lib/spotify.js

https://gist.github.com/adammw/7f192694c3ed0b13f1f9

**Comment by computeralex92** [comment] 2014-06-05 06:26
The fix works without any problem.

**Comment by fakedfaker** [comment] 2014-06-05 08:52
@NeoGeneration Big THX for your hint! This works without any problem! Login to Spotify is working like a charme after changing this by Hand!

**Comment by mawtin** [comment] 2014-06-05 21:13
App still crashes after editing.

**Comment by antac55** [comment] 2014-06-06 02:35
Thanks @NeoGeneration This fixed it for me as well.

**Comment by kennyszub** [comment] 2014-06-12 05:05
Worked for me for the most part - although it wouldn't even start to copy the Starred playlist - copy this to a normal playlist, and don't check the Starred playlist. Thanks!!

**Comment by maxxcrawford** [comment] 2014-06-18 16:42
Hey! Thank you, @NeoGeneration.  This worked for me!

**Comment by MincerRay** [comment] 2014-07-29 14:44
Has anything changed in Spotify's API since Jun 18?  The brute force pong change doesn't work for me.  After logging in with my device ID and device ID password, it either hangs or puts out an error to the console after a few minutes (see below).  If I log in with incorrect credentials, I do get an invalid credentials error message, so I"m pretty sure I am using the right login info.  

% node app.js
portify 0.51
Starting without harmony
Option log level is not valid. Please refer to the README.
Google Login success
Spotify Login failed
{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }

or I get this error:
Spotify Login failed
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by dep-deprecated** [comment] 2014-08-12 13:29
@NeoGeneration made the edit on my install as well, but sadly doesn't fix my problem.  Trying to log in to Spotify and nothing happens when I click 'Submit' :/

**Comment by seffyroff** [comment] 2014-08-19 15:09
I'm guessing whatever the problem is here isn't something that's easy to resolve.  I also get to the Spotify login prompt and then am blocked.  The prompt is active as I get an invalid login message if I provide incorrect credentials.  With correct creds nothing happens at all - nothing in the log or in prompt messages.  I'm using the Github master and also tried merging in changes from above.

**Comment by lohnn** [comment] 2014-08-22 11:29
I, as well, got stuck there, so I started to look into it. After a lot of looking into it, I found [this](https://github.com/1994rstefan/node-spotify-web), from a comment from [here](https://github.com/TooTallNate/node-spotify-web/issues/87), just at the bottom.  They get around the ping-pong problem with using a browser with flash and websockets (or in this case, a connection to a dedicated server with this).
Not REALLY sure how it works, haven't had too much time to look into it.

Anyhow, to use this, just to the [repo](https://github.com/1994rstefan/node-spotify-web), download the .zip and replace the content within spotify-web from inside node_modules to use this one instead. Now logging in to Spotify works at least. I do however stumble upon another problem now, I can't start transfer of playlist. It crashes at:

```
events.js:71 throw arguments[1]; // Unhandled 'error' event
Error: 140097740007296:error:0607907F:digital envelope routines:EVP_PKEY_get1_RSA:expecting an rsa key:../deps/openssl/openssl/crypto/evp/p_lib.c:288:
```

I know this is not the page for this error, but if anyone knows how to get past this error, please let me/us know :)

**Comment by dep-deprecated** [comment] 2014-08-22 13:12
Oh wow @lohnn -- that worked!

**Comment by lohnn** [comment] 2014-08-22 13:14
@dep Great, because I've been trying to find a solution almost non-stop all day and night yesterday! Hehe...

Do you get the same error as me, or does everything work as it should for you now?

**Comment by dep-deprecated** [comment] 2014-08-22 13:15
@lohnn It does indeed! genius work!  thank you for all the effort.  I didn't get the events.js error you did.

My output was:

portify 0.51
Starting without harmony
   info  - socket.io started
Google Login success
Spotify Login success
got 80 playlists
starting transfer...
initiated gmusic

**Comment by lohnn** [comment] 2014-08-22 13:17
Well, I didn't do too much, just put bits and pieces together, and hours of searching :)

Since I don't get it to work, what is your setup? Like what have you done, downloaded and running?

**Comment by dep-deprecated** [comment] 2014-08-22 13:28
@lohnn I used Neogeneration's brute force pong patch above:

Change the following function in portify/data/node_modules/spotify-web/lib/spotify.js
https://gist.github.com/adammw/7f192694c3ed0b13f1f9 - and then your patch as well.

I Googled around and it sounds like it may be a problem with your local install of nodejs.  Do make sure you're on the latest version (Seems like there was a fix issued here: https://github.com/joyent/node/pull/4827)

I've zipped my portify directory here. Not sure if it will help, but who knows!
http://dl.dpeck.net/13WFl

**Comment by lohnn** [comment] 2014-08-22 13:54
Hmm, your source almost worked here! But you were right about the version. Now that I'm running 0.10.25, instead of 0.8 (which I didn't dare not use since that was the version shipped with portify), my source works like it should. Except I can't transfer my starred playlist. Hmmm, well that is a minor problem though :)

Thanks man!

**Comment by dep-deprecated** [comment] 2014-08-22 13:59
@lohnn Glad we were able to help each other :)

**Comment by svoznyuk** [comment] 2014-08-22 15:13
for windows users you might need to change the metadata.proto file as well, here's how by @yodis
https://github.com/mauimauer/portify/issues/95 (scroll towards the bottom) 
thanks to @lohnn and @dep you guys are awesome

**Comment by yrahcaz** [comment] 2014-08-23 04:16
I am getting this error :( ignore my folder name hahaha

```
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
    at ProtoBuf.Reflect.Field.verifyValue (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\P
rotoBuf.js:2321:27)
    at Message.add (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:1693:53)
    at ProtoBuf.Reflect.Message.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\Prot
oBuf.js:2137:29)
    at ProtoBuf.Reflect.Field.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\ProtoB
uf.js:2594:46)
    at ProtoBuf.Reflect.Message.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\Prot
oBuf.js:2137:51)
    at Message.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:1982:41)
    at Function.protobufjs_parse_wrapper [as parse] (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\schemas.js:
98:39)
    at Spotify._parse (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\spotify.js:1294:20)
    at parseData (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\spotify.js:598:18)
    at C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\spotify.js:586:20
I am getting this error :(
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
    at ProtoBuf.Reflect.Field.verifyValue (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\P
rotoBuf.js:2321:27)
    at Message.add (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:1693:53)
    at ProtoBuf.Reflect.Message.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\Prot
oBuf.js:2137:29)
    at ProtoBuf.Reflect.Field.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\ProtoB
uf.js:2594:46)
    at ProtoBuf.Reflect.Message.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\Prot
oBuf.js:2137:51)
    at Message.decode (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:1982:41)
    at Function.protobufjs_parse_wrapper [as parse] (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\schemas.js:
98:39)
    at Spotify._parse (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\spotify.js:1294:20)
    at parseData (C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\spotify.js:598:18)
    at C:\Users\Zach\Desktop\fart\data\node_modules\spotify-web\lib\spotify.js:586:20
```

---------scratch the below for now...-----------
@dep Hey man, i was trying to bring together all the fixes to get it to work and wasnt having luck. I downloaded your source and it worked perfectly, thanks so much!
@lohnn thanks for helping dep and vice-versa!

**Comment by svoznyuk** [comment] 2014-08-25 16:21
@lzngl https://github.com/mauimauer/portify/issues/95 <-- this is the link for the metadata issue I'll just paste the fix here by @yodis

It seams like the spotify-api has been changed or appended to. And the error is in the dependency spotify-web rather than in portify.

I have no experience in nodejs, or the spotify api. So everything i say should not be belived and is probably wrong. However, after you do the npm install, you can make make changes to the proto files which according to my understanding describes the data-structures of the spotify-api.

The changes needed to make it work (at least for me), is in the metadata.proto file.

enum Catalogue {
AD = 0;
SUBSCRIPTION = 1;
SHUFFLE = 3;
}

Needs to be extended for the value 4, i have no idea what 4 means, my guess is that it is some kind of premium flag (I have premium).

enum Catalogue {
AD = 0;
SUBSCRIPTION = 1;
SHUFFLE = 3;
PremiumOrWhat = 4;
}

message AudioFile {
enum Format {
OGG_VORBIS_96 = 0;
OGG_VORBIS_160 = 1;
OGG_VORBIS_320 = 2;
MP3_256 = 3;
MP3_320 = 4;
MP3_160 = 5;
MP3_96 = 6;
}
optional bytes file_id = 1;
optional Format format = 2;
}

Here spotify seams to now also include the value 7, again i have no idea what this means. Since we are only intrested in the playlist, the actual encoding should be pretty irelevant.

message AudioFile {
enum Format {
OGG_VORBIS_96 = 0;
OGG_VORBIS_160 = 1;
OGG_VORBIS_320 = 2;
MP3_256 = 3;
MP3_320 = 4;
MP3_160 = 5;
MP3_96 = 6;
MP3_WTF = 7;
}
optional bytes file_id = 1;
optional Format format = 2;
}

Here you can find my complete file:
https://gist.github.com/yodiz/9902070

after you change the protofile, it seams like spotify-web uses the compiled version of the proto file, describes in the .desc equivalent. You can compile to .desc using google protoc. Available and described at https://code.google.com/p/protobuf/.

I simply copied protoc.exe to the directory containing the metadata.proto file, and execute the following from the cmd-prompt/powershell. "./protoc.exe --descriptor_set_out=metadata.desc --include_imports metadata.prot"

All of of my playlists except one worked after that. I get an unrelated error on the last one.

Again - this is not very userfriendly and probably erroneous in many ways. My fix, for obvious reasons is not good enough to go into the spotify-web project :).

**Comment by calibu** [comment] 2014-09-01 05:38
First of all thank you guys @dep and @lohnn. I've tried @dep zipped portify directory, but it gives me following error while connecting to Spotify with correct credentials:

Spotify Login failed
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

does anyone know how to resolve this? Thanks in advance.

**Comment by simonflore** [comment] 2014-09-02 09:59
Same problem here as @calibu

**Comment by antipop001** [comment] 2014-09-17 01:05
I am having the same issue as the last 2 posters. Does anyone have an idea on this one?

Spotify Login failed
{ [Error: connect ECONNREFUSED]
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect' }

**Comment by seffyroff** [comment] 2014-09-18 18:37
Same here - this was working up until recently.  I guess someone changed something in the Spotify API?

**Comment by acrombez** [comment] 2014-10-07 19:55
After applying above suggested changes I succeeded to run portify, sign in to Google and Spotify and get a list of my spotify playlists. However when I select a playlist to create it into Google Music, I get a parsing error. 
By putting some more logging in the code I could see that the search done with the search2 function returns a result from google but that the error occurs when parsing this result:

```
            try {
                console.log(response);
                var parsed = JSON.parse(response);
                if(cb)
                    cb(parsed);
            } catch(e) {
                console.error("gmusic:search2(), parsing failed");
            }
```

Possibly Google changed the content of their result. Are other people having this problem? Is there a way to fix the parsing?

Many thanks in advance.

**Comment by benknight** [comment] 2014-10-22 01:21
I also got through this whole maze of solutions to end up where @acrombez is.  Here's the script's output:

```
$ node app.js 
portify 0.51
Starting without harmony
Option log level is not valid. Please refer to the README.
Google Login success
Spotify Login success
got 42 playlists
starting transfer...
initiated gmusic
created playlist Winter 2013(spotify:user:benjaminknight:playlist:2UEk6sSwhGtiLM2KfXkgTP) on google music
fetch info about playlist in spotify
gotPlaylistLength()
gmusic:search2(), parsing failed
trackDone() 1/33
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
trackDone() 2/33
gmusic:search2(), parsing failed
trackDone() 3/33
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
trackDone() 4/33
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
trackDone() 5/33
trackDone() 6/33
gmusic:search2(), parsing failed
trackDone() 7/33
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
trackDone() 8/33
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
gmusic:search2(), parsing failed
trackDone() 9/33
```

**Comment by dep-deprecated** [comment] 2014-10-22 10:23
Looks like the API has changed on one side or the other.  It'll take some time to figure out if it's fixable.  I'll be a able to take a better look next week.

**Comment by Rosewellzz** [comment] 2014-10-26 22:17
@dep do you have a copy of the whole program, that you compiled, the link you placed earlier is broken. cheers.

**Comment by dep-deprecated** [comment] 2014-10-26 22:31
@Rosewellzz I'll update my reply above with an updated, working link. Thanks for pointing that out (updated)

**Comment by grout58** [comment] 2014-10-28 17:02
@dep your fix worked getting passed the spotify login, but now after selecting playlists and hitting export i get this:

Google Login success
Spotify Login success
got 3 playlists
starting transfer...
initiated gmusic
created playlist Songs 2(spotify:user:grout58:playlist:68cSx4tWgeTMuxHP88cEth) on google music
fetch info about playlist in spotify
gotPlaylistLength()

**Comment by Rosewellzz** [comment] 2014-10-28 23:16
@dep , thanks, got past the spotify login now, selected a playlist or two, tried to transfer but am just presented with a screen 

![screen](https://cloud.githubusercontent.com/assets/9408562/4818805/59cf2efc-5ef8-11e4-9eee-555d9204b970.jpg)

The playlist name appears in google play, but contains no songs. any ideas?

**Comment by benknight** [comment] 2014-10-29 05:52
Yep unfortunately this seems to be everyone's fate.  You're not doing anything wrong.  It's just broken and needs to be fixed :)

**Comment by vanshg** [comment] 2014-11-13 06:09
Is there any other way to transfer playlists from Spotify to GPMAA?

**Comment by nilicule** [comment] 2014-11-23 10:56
If you're using the archive that @dep provided and you're getting:

```
    gmusic:search2(), parsing failed
```

then you might have to update some JSON indexes in app.js to get things working.

Details can be found at https://github.com/nilicule/portify/commit/bd6c69e8854c58736431aa28984697011fa64633

**Comment by andrew01ait** [comment] 2014-11-26 12:35
1) I've installed NodeJS and NPM http://www.hacksparrow.com/install-node-js-and-npm-on-windows.html 
2) checked out the portify repository installed the application and fired it up.
3) After having gotten stuck at the Spotify login screen I followed 'lohnn's comment from 22 Aug and exchanged the content of spotify-web with this repository https://github.com/1994rstefan/node-spotify-web which brought me over the login step
4) I see 5 playlists. These are the ones I marked as public or which I have subscribed to in spotify. No regular playlists?!
5) When trying to import one of the 4 Spotify Playlists to GPM I receive a 404

Google Login success
Spotify Login success
got 4 playlists
starting transfer...
initiated gmusic
created playlist Starred Tracks(hm://playlist/user/119876239/starred) on google music
fetch info about playlist in spotify
spotify error: Error: Client Error: Not Found (404)

Any hints?

**Comment by decomush** [comment] 2014-11-27 18:33
Hey @andrew01ait. Just got the sma eerror. Just make a new playlist from you starred ones. As stated here: https://github.com/mauimauer/portify/issues/100

**Comment by DoctorUg** [comment] 2015-01-10 13:05
I am having the same issue as the OP, except that 'lohnn's workaround no longer worked. I tried using the repository https://github.com/TooTallNate/node-spotify-web and now at least get a login failed message, compared to just nothing with the original or the workaround above:

portify 0.51
Starting without harmony
Option log level is not valid. Please refer to the README.
Google Login success
Spotify Login failed
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

**Comment by dep-deprecated** [comment] 2015-01-14 17:07
This is brand new. You might have more luck with it:

https://github.com/rckclmbr/pyportify

just did a clean install of this and it worked flawlessly.

**Closed as completed** 2015-01-18 13:25 UTC

**Comment by jeffrdrew** [comment] 2015-01-19 10:54
pyportify worked flawlessly for me.  Thanks!   I just want to point out that on Mac OSX, $ pyportify returned 'command not found'.   I ran with '$ python ./server.py'

**Comment by sxyCode** [comment] 2015-01-25 16:35
is it possible to get pyportify working on windows? since theres only a description for mac, ubuntu, fedora

**Comment by tjgoulet** [comment] 2015-04-15 02:43
@dep Thanks!   node version was really, really annoying to get working!     It's April 2015 and pyportify got the job done!    Didn't find matches for some songs that it should have but most of it came over.  (at least it also provided an output of what didn't come over as well)
