### ISSUE TITLE
Error: TODO: implement!

### ISSUE THREAD

**Issue by deanpcmad** [mauimauer/portify#84] opened 2014-02-25 17:54 UTC
I've just tried to use portify but I get this error when signing in with Spotify

![](http://s.vou.pe.s3.amazonaws.com/ede6I.png)

I'm using node v0.10.26

**Comment by dukejansen** [comment] 2014-02-27 19:53
I believe this is a duplicate of https://github.com/mauimauer/portify/issues/79, which has a workaround documented in a comment by https://github.com/dimfeld.

**Comment by gosuto-inzasheru** [comment] 2014-03-07 11:30
The workaround described there worked for me!

**Comment by josteink** [comment] 2014-03-18 20:19
Seconding that. That workaround is still needed at this point, but it does seem to work.

**Comment by alesch** [comment] 2014-03-19 20:59
I confirm that the workaround is still needed.

**Closed as completed** 2016-02-20 18:13 UTC
